# Classification of presence of a gene in a person

Importing libraries for processing the dataset

In [1]:
import numpy as np 
import pandas as pd
import warnings

Importing libraries for classification

In [2]:
from sklearn.metrics import confusion_matrix 
from sklearn.preprocessing import LabelEncoder
from sklearn.cross_validation import train_test_split 
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report
from sklearn import metrics 

/usr/local/lib/python3.5/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Building the dataset for training

In [3]:
def buildTrainDataset():
    # Collating the data from 15 files into one dataframe
    dataset_list = []
    files = open('listfile_org','r')

    for file in files:
        file=file.strip('\n')
        print(file)
        df = pd.read_csv(file, sep='\t')
        df = df[['ID_REF','VALUE', 'ABS_CALL','Detection p-value']]
        dataset_list.append(df)

    dataset = pd.concat(dataset_list)
    
    # Encoding non-numeric data
    label_encoder = LabelEncoder()
    dataset['ID_REF']   = label_encoder.fit_transform(dataset['ID_REF'])
    dataset['ABS_CALL'] = label_encoder.fit_transform(dataset['ABS_CALL'])

    return dataset

dataset = buildTrainDataset()

Dataset/GSM6577.txt
Dataset/GSM6578.txt
Dataset/GSM6579.txt
Dataset/GSM6580.txt
Dataset/GSM6581.txt
Dataset/GSM6582.txt
Dataset/GSM6583.txt
Dataset/GSM6584.txt
Dataset/GSM6227.txt
Dataset/GSM6571.txt
Dataset/GSM6572.txt
Dataset/GSM6573.txt
Dataset/GSM6574.txt
Dataset/GSM6575.txt
Dataset/GSM6576.txt


Splitting the data for testing

In [5]:
def prepClfData(balance_data): 
  
    # Seperating the target variable 
    X = balance_data[['ID_REF','VALUE', 'Detection p-value']] 
    Y = balance_data['ABS_CALL'] 

    #Opening the test data file
    test_data = pd.read_csv('Dataset/GSM6544.txt', sep='\t')

    label_encoder = LabelEncoder()
    test_data['ID_REF']=  label_encoder.fit_transform(test_data['ID_REF'])
    test_data['ABS_CALL']=  label_encoder.fit_transform(test_data['ABS_CALL'])

    #Splitting the data for training and testing
    X_train = balance_data[['ID_REF','VALUE', 'Detection p-value']] 
    X_test = test_data[['ID_REF','VALUE', 'Detection p-value']]
    y_train = balance_data['ABS_CALL']
    y_test = test_data['ABS_CALL']
      
    return X, Y, X_train, X_test, y_train, y_test


X, Y, X_train, X_test, y_train, y_test = prepClfData(dataset)

Using Naive-Bayes Classifier to train the data

In [6]:
def train_using_gauss(X_train, X_test, y_train): 

    # Creating the classifier object 
    GaussNB = GaussianNB()
    
    #Perform training
    GaussNB.fit(X_train,y_train)
    return(GaussNB)

GaussNB = train_using_gauss(X_train,X_test,y_train)

Function to make the prediction

In [7]:
def prediction(X_test, clf_object): 
    # Predicton on test with naive Bayes
    y_pred = clf_object.predict(X_test) 
    print("Predicted values:") 
    print(y_pred) 
    return y_pred

Making the prediciton for the testing data

In [8]:
print("Results Using Naive Bayes:")
y_pred = prediction(X_test, GaussNB)

Results Using Naive Bayes:
Predicted values:
[2 0 0 ... 2 0 2]


Accuracy measure for the predicted data

In [9]:
# Function to calculate accuracy 
def evaluate_prediction(y_test, y_pred): 
      
    print("Confusion Matrix: ")
    print(confusion_matrix(y_test, y_pred),'\n')
      
    print("Report : ")
    print(classification_report(y_test, y_pred),'\n')
    
    print ("Accuracy : ", accuracy_score(y_test,y_pred)*100,'%','\n') 

evaluate_prediction(y_test, y_pred) 

Confusion Matrix: 
[[ 8586     0   232]
 [  274     0    71]
 [ 2380     0 11267]] 

Report : 
             precision    recall  f1-score   support

          0       0.76      0.97      0.86      8818
          1       0.00      0.00      0.00       345
          2       0.97      0.83      0.89     13647

avg / total       0.88      0.87      0.87     22810
 

Accuracy :  87.03638754932047 % 



/usr/local/lib/python3.5/dist-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
